services:
  - type: web
    name: live-chat
    env: rust
    buildCommand: cargo build --release
    startCommand: ./target/release/your-binary-name
    envVars:
      - key: SERVER_PORT
        value: 8080
